demo_base:
  addons:
    - {addonkey: demo_base,      file: 2643}  # 2.6.4
    - {addonkey: markitup,       file: 2588}  # 3.2.0
    - {addonkey: phpmailer,      file: 1821}  # 2.1.2
    - {addonkey: redactor2,      file: 2514}  # 3.5.0
    - {addonkey: sprog,          file: 1446}  # 1.1.0
    - {addonkey: yform,          file: 2695}  # 3.0.0
  activate:
    - phpmailer
    - markitup
    - redactor2
    - sprog
    - yform
    - demo_base
  dbimport:
    - demo_base.sql
  fileimport:
    - demo_base.tar.gz

demo_community:
  addons:
    - {addonkey: demo_community, file: 2085}  # 2.1.0
    - {addonkey: markitup,       file: 2078}  # 3.0.2
    - {addonkey: ycom,           file: 1987}  # 2.0
    - {addonkey: yform,          file: 1986}  # 2.2
  activate:
    - phpmailer
    - markitup
    - yform
    - yform/geo
    - ycom
    - demo_community
  dbimport:
    - demo_community.sql
  fileimport:
    - demo_community.tar.gz

demo_onepage:
  addons:
    - {addonkey: demo_onepage,   file: 2641}  # 1.2.2
    - {addonkey: developer,      file: 2274}  # 3.7.0
    - {addonkey: markitup,       file: 2588}  # 3.2.0
    - {addonkey: mblock,         file: 2557}  # 2.2.3
  activate:
    - developer
    - markitup
    - mblock
    - be_style/customizer
    - demo_onepage
  dbimport:
    - demo_onepage.sql
  fileimport:
    - demo_onepage.tar.gz

demo_fullpage:
  addons:
    - {addonkey: demo_fullpage,  file: 2167}  # 1.1.0beta
  activate:
    - demo_fullpage
  dbimport:
    - demo_fullpage.sql
  fileimport:
    - demo_fullpage.tar.gz
